<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Velvet.Core\Velvet.Core.csproj" />
    <ProjectReference Include="..\Velvet.WebGL\Velvet.WebGL.csproj" />
    <PackageReference Include="Microsoft.JSInterop" Version="9.0.11" />
  </ItemGroup>

</Project>
