<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Velvet.Core\Velvet.Core.csproj" />
    <PackageReference Include="Microsoft.JSInterop" Version="10.0.0" />
    <PackageReference Include="Microsoft.NET.Runtime.WebAssembly.Sdk" Version="10.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="wwwroot\**" />
  </ItemGroup>

</Project>
