<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Velvet.Core\Velvet.Core.csproj" />
    <PackageReference Include="Microsoft.JSInterop" Version="9.0.0" />
    <PackageReference Include="Microsoft.NET.Runtime.WebAssembly.Sdk" Version="9.0.0" />
  </ItemGroup>

  <ItemGroup>
    <None Include="dist\velvet.js">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
